function data()

return {

	ru = {
		["Silver"] = "Серебро",
		["Slag"] = "Шлак",
		["Meat"] = "Мясо",
		["Marble mine"] = "Мраморный карьер",
		["Coffee farm"] = "Кофейная плантация",
		["Coffee processing plant"] = "Кофейный завод",
		["Livestock farm"] = "Животноводческая ферма",
		["Meat processing plant"] = "Мясоперерабатывающий завод",
		["Paper mill"] = "Бумажная фабрика",
		["Silver ore mine"] = "Серебряный рудник",
		["Oil sand mine"] = "Кариер нефтеносного песка",
		["Silver mill"] = "Сереброплавильный завод",
		["Alcohol distillery"] = "Спиртзавод",
		["Silver products"] = "Серебрение изделия",
		["Silver products factory"] = "Фабрика серебряных изделий",
		["War materials factory"] = "Военный завод",
		["Sugar Farm"] = "Сахарная плантация",
		["Asphalt plant"] = "Асфальтовый завод",
		["Gold ore"] = "Золотоносная руда",
		["Gold"] = "Золото",
		["Gold products"] = "Золотые изделия",
		["Gold ore mine"] = "Золотой рудник",
		["Gold mill"] = "Золотоплавильный завод",
		["Gold products factory"] = "Фабрика золотых изделий",
		["Lubricants"] = "Смазочные материалы",
		["Lubricants refinery"] = "Завод смазочных материалов",
		["Bauxite"] = "Бокситы",
		["Aluminum"] = "Aлюминий",
		["Copper ore"] = "Медная руда",
		["Copper"] = "Медь",
		["Bauxite mine"] = "Бокситовый рудник",
		["Aluminum mill"] = "Алюминиевый завод",
		["Copper ore mine"] = "Медная шахта",
		["Copper mill"] = "Медеплавильный завод",
		["Tobacco"] = "Табак",
		["Cigar factory"] = "фабрика сигар",
		["Separation plant"] = "Разделительный завод",
		["Tobacco plantation"] = "Табачная плантация",
		["Recycling plant"] = "Завод по переработке",
		["Cannery"] = "Консервный завод",
		["Bioplastic plant"] = "Завод биопластика",
		["Fuel refinery"] = "Топливный завод",
		["Alcoholic drinks"] = "Алкогольные напитки",
		["Bottling plant"] = "Завод по розливу",
		["Waterworks"] = "Водопроводная станция",
		["Power plant"] = "Электростанция",
		["Tropical Fruit"] = "Тропический фрукт"
	},
}
end
